apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: sidhu-cluster
  labels:
    environment: dev 
    app: fe-developer
  annotations:
    description: "this pod for annotations"
    maintainer: "siddhartha@surnoi.com"
    git-commit: "hi this sidhu"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
